version: "3.8"

services:
  etcd2:
    build:
      context: ./etcd
    container_name: etcd2
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.16.103.13:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://172.16.103.13:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://172.16.103.14:2380,etcd2=http://172.16.103.13:2380,etcd3=http://172.16.103.2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    command: >
      /bin/sh -c "etcd --listen-client-urls=http://0.0.0.0:2379"
    ports:
      - "2379:2379"
      - "2380:2380"

  servidor2:
    build:
      context: ./servidor
    container_name: servidor2
    environment:
      - ETCD_ENDPOINTS=http://172.16.103.14:2379,http://172.16.103.13:2379,http://172.16.103.2:2379
    ports:
      - "8080:8080"
    depends_on:
      - etcd2
    stdin_open: true
    tty: true
